version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: eshop_mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'eshop'
      MYSQL_USER: 'eshop'
      MYSQL_PASSWORD: 'eshop!@#'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    volumes:
      - mysqldb-data:/var/lib/mysql
    command: [
      'mysqld',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--skip-character-set-client-handshake',
    ]
  
  adminer:
    image: adminer:latest
    container_name: eshop_adminer
    ports:
      - 3307:3307

volumes:
  mysqldb-data:
